# Netlify configuration file

[build]
  publish = "dist"
  command = "npm run build"
  ignore_warnings = true
  
[build.environment]
  # Ensure Node.js version is compatible
  NODE_VERSION = "16"
  # Force clean build
  NETLIFY_USE_YARN = "false"
  NETLIFY_YARN_WORKSPACES = "false"
  # Supabase environment variables
  VITE_SUPABASE_URL = "https://cdskvspoucbfwnhiofoy.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkc2t2c3BvdWNiZnduaGlvZm95Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MzYyNDgsImV4cCI6MjA2MDMxMjI0OH0.I7TKi8sjt5iXVa64BqWA3ASVPCsDWWJwAWUGQ_6hfAg"
  VITE_AUTH_REDIRECT_URL = "https://momentum-testt.netlify.app/auth/callback"

# Ensure all routes are handled by the Vue Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Special handling for JavaScript files
[[headers]]
  for = "**/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"

# Special handling for CSS files
[[headers]]
  for = "**/*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

# Disable cache for HTML and root files
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    X-Content-Type-Options = "nosniff"