# Netlify configuration file

[build]
  publish = "dist"
  command = "npm run build"
  
[build.environment]
  # Ensure Node.js version is compatible
  NODE_VERSION = "16"

# Ensure all routes are handled by the Vue Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Add cache control for assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"